########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../..

# Enter object files here:
OBJECTS	  = error.o success.o

# Enter addition commands for targets all and clean here:
ALLCMD1   = cd fs && make
ALLCMD2   = cd misc && make
CLEANCMD1 = cd fs && make clean
CLEANCMD2 = cd misc && make clean

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
