 /* The SMOOTH Windowing Toolkit
  * Copyright (C) 1998-2002 Robert Kausch <robert.kausch@gmx.net>
  *
  * This library is free software; you can redistribute it and/or
  * modify it under the terms of the "Artistic License".
  *
  * THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
  * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. */

#ifndef __OBJSMOOTH_METRICS_
#define __OBJSMOOTH_METRICS_

#include <smooth/metrics.h>
#include <smooth/definitions.h>
#include <smooth/stk.h>
#include <smooth/toolkit.h>

int	 METRIC_TITLEBARHEIGHT;
int	 METRIC_TBBUTTONBOXOFFSETX;
int	 METRIC_TBBUTTONBOXOFFSETY;
int	 METRIC_TBBUTTONBOXWIDTH;
int	 METRIC_TBBUTTONBOXHEIGHT;
int	 METRIC_TBBUTTONSIZE;
int	 METRIC_TBBUTTONOFFSETX;
int	 METRIC_TBBUTTONOFFSETY;
int	 METRIC_TBTEXTOFFSETX;
int	 METRIC_TBTEXTOFFSETY;
int	 METRIC_TBICONSIZE;
int	 METRIC_TBICONOFFSET;

int	 METRIC_MENUBARHEIGHT;
int	 METRIC_MBTEXTOFFSETX;
int	 METRIC_MBTEXTOFFSETY;
int	 METRIC_MBENTRYSPACING;
int	 METRIC_MBENTRYHEIGHT;

int	 METRIC_ICONBARHEIGHT;
int	 METRIC_IBICONOFFSETX;
int	 METRIC_IBICONOFFSETY;
int	 METRIC_IBICONSIZE;
int	 METRIC_IBENTRYSPACING;
int	 METRIC_IBARROWOFFSETY;
int	 METRIC_IBARROWSIZEX;
int	 METRIC_IBARROWSIZEY;

int	 METRIC_STATUSBARHEIGHT;
int	 METRIC_SBTEXTOFFSETX;
int	 METRIC_SBTEXTOFFSETY;

int	 METRIC_PBHEIGHT;
int	 METRIC_PBWIDTH;
int	 METRIC_PBTEXTOFFSETY;

int	 METRIC_GBTEXTOFFSETY;

int	 METRIC_POPUPENTRYSIZE;
int	 METRIC_POPUPARROWOFFSETY;

int	 METRIC_CHECKBOXOFFSETXY;
int	 METRIC_CHECKBOXTEXTOFFSETY;

int	 METRIC_OPTBOXOFFSETXY;
int	 METRIC_OPTBOXTEXTOFFSETY;

int	 METRIC_EDITBOXLINEHEIGHT;

int	 METRIC_COMBOBOXOFFSETX;
int	 METRIC_COMBOBOXARROWOFFSETY;
int	 METRIC_COMBOBOXARROWOFFSETX;
int	 METRIC_COMBOBOXTEXTOFFSETXY;

int	 METRIC_REGISTEROFFSETY;
int	 METRIC_REGISTERTEXTOFFSETX;
int	 METRIC_REGISTERTEXTOFFSETY;

int	 METRIC_TREEVIEWENTRYHEIGHT;

int	 METRIC_SLIDERAREAWIDTH;
int	 METRIC_SLIDERAREAHEIGHT;
int	 METRIC_SLIDERAREAOFFSETX;
int	 METRIC_SLIDERAREAOFFSETY;

int	 METRIC_LISTBOXENTRYHEIGHT;
int	 METRIC_LISTBOXTEXTOFFSETXY;
int	 METRIC_LISTBOXSBOFFSET;
int	 METRIC_LISTBOXSBSIZE;

void SMOOTHSetMetrics()
{
	HDC	 dc = GetContext(0);

#ifdef __WIN32__
	int	 dpiy = GetDeviceCaps(dc, LOGPIXELSY);
#endif

	FreeContext(0, dc);

#ifdef __WIN32__
	switch (dpiy)
	{
		default:
		case 96:
			METRIC_TITLEBARHEIGHT = 19;
			METRIC_TBBUTTONBOXOFFSETX = 39;
			METRIC_TBBUTTONBOXOFFSETY = 2;
			METRIC_TBBUTTONBOXWIDTH = 35;
			METRIC_TBBUTTONBOXHEIGHT = 13;
			METRIC_TBBUTTONSIZE = 7;
			METRIC_TBBUTTONOFFSETX = 4;
			METRIC_TBBUTTONOFFSETY = 5;
			METRIC_TBTEXTOFFSETX = 3;
			METRIC_TBTEXTOFFSETY = 2;
			METRIC_TBICONSIZE = 16;
			METRIC_TBICONOFFSET = 3;

			METRIC_MENUBARHEIGHT = 18;
			METRIC_MBTEXTOFFSETX = 12;
			METRIC_MBTEXTOFFSETY = 4;
			METRIC_MBENTRYSPACING = 9;
			METRIC_MBENTRYHEIGHT = 14;

			METRIC_ICONBARHEIGHT = 18;
			METRIC_IBICONOFFSETX = 12;
			METRIC_IBICONOFFSETY = 6;
			METRIC_IBICONSIZE = 12;
			METRIC_IBENTRYSPACING = 6;
			METRIC_IBARROWOFFSETY = 4;
			METRIC_IBARROWSIZEX = 7;
			METRIC_IBARROWSIZEY = 3;

			METRIC_STATUSBARHEIGHT = 16;
			METRIC_SBTEXTOFFSETX = 4;
			METRIC_SBTEXTOFFSETY = 1;

			METRIC_PBTEXTOFFSETY = 2;

			METRIC_GBTEXTOFFSETY = 7;

			METRIC_POPUPENTRYSIZE = 16;
			METRIC_POPUPARROWOFFSETY = 3;

			METRIC_CHECKBOXOFFSETXY = 3;
			METRIC_CHECKBOXTEXTOFFSETY = 1;

			METRIC_OPTBOXOFFSETXY = 3;
			METRIC_OPTBOXTEXTOFFSETY = 1;

			METRIC_EDITBOXLINEHEIGHT = 15;

			METRIC_COMBOBOXOFFSETX = 16;
			METRIC_COMBOBOXARROWOFFSETY = 8;
			METRIC_COMBOBOXARROWOFFSETX = 12;
			METRIC_COMBOBOXTEXTOFFSETXY = 3;

			METRIC_REGISTEROFFSETY = 19;
			METRIC_REGISTERTEXTOFFSETX = 7;
			METRIC_REGISTERTEXTOFFSETY = 2;

			METRIC_TREEVIEWENTRYHEIGHT = 16;

			METRIC_SLIDERAREAWIDTH = 9;
			METRIC_SLIDERAREAHEIGHT = 18;
			METRIC_SLIDERAREAOFFSETX = 4;
			METRIC_SLIDERAREAOFFSETY = 8;

			METRIC_LISTBOXENTRYHEIGHT = 15;
			METRIC_LISTBOXTEXTOFFSETXY = 2;
			METRIC_LISTBOXSBOFFSET = 16;
			METRIC_LISTBOXSBSIZE = 18;

			break;
		case 120:
			METRIC_TITLEBARHEIGHT = 25;
			METRIC_TBBUTTONBOXOFFSETX = 46;
			METRIC_TBBUTTONBOXOFFSETY = 3;
			METRIC_TBBUTTONBOXWIDTH = 40;
			METRIC_TBBUTTONBOXHEIGHT = 16;
			METRIC_TBBUTTONSIZE = 8;
			METRIC_TBBUTTONOFFSETX = 5;
			METRIC_TBBUTTONOFFSETY = 6;
			METRIC_TBTEXTOFFSETX = 5;
			METRIC_TBTEXTOFFSETY = 3;
			METRIC_TBICONSIZE = 20;
			METRIC_TBICONOFFSET = 4;

			METRIC_MENUBARHEIGHT = 22;
			METRIC_MBTEXTOFFSETX = 13;
			METRIC_MBTEXTOFFSETY = 5;
			METRIC_MBENTRYSPACING = 10;
			METRIC_MBENTRYHEIGHT = 17;

			METRIC_ICONBARHEIGHT = 22;
			METRIC_IBICONOFFSETX = 14;
			METRIC_IBICONOFFSETY = 6;
			METRIC_IBICONSIZE = 16;
			METRIC_IBENTRYSPACING = 7;
			METRIC_IBARROWOFFSETY = 5;
			METRIC_IBARROWSIZEX = 9;
			METRIC_IBARROWSIZEY = 4;

			METRIC_STATUSBARHEIGHT = 19;
			METRIC_SBTEXTOFFSETX = 5;
			METRIC_SBTEXTOFFSETY = 1;

			METRIC_PBTEXTOFFSETY = 3;

			METRIC_GBTEXTOFFSETY = 8;

			METRIC_POPUPENTRYSIZE = 19;
			METRIC_POPUPARROWOFFSETY = 4;

			METRIC_CHECKBOXOFFSETXY = 4;
			METRIC_CHECKBOXTEXTOFFSETY = 2;

			METRIC_OPTBOXOFFSETXY = 4;
			METRIC_OPTBOXTEXTOFFSETY = 2;

			METRIC_EDITBOXLINEHEIGHT = 17;

			METRIC_COMBOBOXOFFSETX = 18;
			METRIC_COMBOBOXARROWOFFSETY = 9;
			METRIC_COMBOBOXARROWOFFSETX = 13;
			METRIC_COMBOBOXTEXTOFFSETXY = 4;

			METRIC_REGISTEROFFSETY = 22;
			METRIC_REGISTERTEXTOFFSETX = 8;
			METRIC_REGISTERTEXTOFFSETY = 3;

			METRIC_TREEVIEWENTRYHEIGHT = 18;

			METRIC_SLIDERAREAWIDTH = 11;
			METRIC_SLIDERAREAHEIGHT = 22;
			METRIC_SLIDERAREAOFFSETX = 5;
			METRIC_SLIDERAREAOFFSETY = 10;

			METRIC_LISTBOXENTRYHEIGHT = 18;
			METRIC_LISTBOXTEXTOFFSETXY = 3;
			METRIC_LISTBOXSBOFFSET = 18;
			METRIC_LISTBOXSBSIZE = 20;

			break;
	}
#endif
}

void SMOOTHSetMeasurement(int type)
{
	HDC	 dc = GetContext(0);

#ifdef __WIN32__
	int	 dpiy = GetDeviceCaps(dc, LOGPIXELSY);
#else
	int	 dpiy = 0;
#endif

	FreeContext(0, dc);

	switch (type)
	{
		case SMT_UNITS:
			switch (dpiy)
			{
				default:
				case 96:
					SMOOTH::Setup::FontSize = 1.00;
					break;
				case 120:
					SMOOTH::Setup::FontSize = 1.25;
					break;
			}
			break;
		default:
		case SMT_PIXELS:
			SMOOTH::Setup::FontSize = 1.00;
			break;
	}
}

#endif
