########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../..

# Change these variables to fit your project:
LOCALDLL  = myactivearea
IMPORTLIB = libmyactivearea.a

MYCCOPTS  = -D SMOOTH_PLUGIN_DLL

# Enter object files here:
OBJECTS	  = myactivearea.o

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
ALLCMD3   =
CLEANCMD1 =
CLEANCMD2 =
CLEANCMD3 =

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-commands
