########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../..

# Change these variables to fit your project:
GLOBALLIB   = libfribidi.a
MYCCOPTS    = -I$(SRCDIR) -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_STRINGIZE=1

# Enter object files here:
OBJECTS	    = fribidi.o fribidi-arabic.o fribidi-bidi.o fribidi-bidi-types.o fribidi-brackets.o fribidi-char-sets.o fribidi-char-sets-cap-rtl.o fribidi-char-sets-cp1255.o fribidi-char-sets-cp1256.o fribidi-char-sets-iso8859-6.o fribidi-char-sets-iso8859-8.o fribidi-char-sets-utf8.o fribidi-deprecated.o fribidi-joining.o fribidi-joining-types.o fribidi-mirroring.o fribidi-run.o fribidi-shape.o

## Do not change anything below this line. ##

include $(dir $(firstword $(MAKEFILE_LIST)))/$(SMOOTH_PATH)/Makefile-commands
