########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../../../..

# Enter object files here:
OBJECTS	  = combobox.o list.o listbox.o listboxheader.o listentry.o listentryseparator.o

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
