########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../..

# Change these variables to fit your project:
GLOBALLIB   = libfribidi.a
MYCCOPTS    = -I.

# Enter object files here:
OBJECTS	    = fribidi.o fribidi-arabic.o fribidi-bidi.o fribidi-bidi-types.o fribidi-deprecated.o fribidi-joining.o fribidi-joining-types.o fribidi-mem.o fribidi-mirroring.o fribidi-run.o fribidi-shape.o

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
