########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../..

# Enter object files here:
OBJECTS	  = layer.o widget.o

# Enter addition commands for targets all and clean here:
ALLCMD1   = cd basic && make
ALLCMD2   = cd hotspot && make
ALLCMD3   = cd multi && make
ALLCMD4   = cd special && make
CLEANCMD1 = cd basic && make clean
CLEANCMD2 = cd hotspot && make clean
CLEANCMD3 = cd multi && make clean
CLEANCMD4 = cd special && make clean

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
