########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../../../..

# Enter object files here:
OBJECTS	  = menu.o menubar.o menubarentry.o menuentry.o micromenu.o popupmenu.o popupmenuentry.o popupmenuentrycheck.o popupmenuentryoption.o

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
