########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../..

# Change these variables to fit your project:
GLOBALLIB   = libiconv.a
MYCCOPTS    = -DLIBICONV_PLUG -D_ICONVDLL_ -I.

# Enter object files here:
OBJECTS	    = iconv.o localcharset.o

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
