########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../..

# Enter object files here:
OBJECTS	  = colordlg.o dialog.o fontdlg.o messagebox.o splashscreen.o tipodaydlg.o

# Enter addition commands for targets all and clean here:
ALLCMD1   = cd directory && $(MAKE)
ALLCMD2   = cd file && $(MAKE)
CLEANCMD1 = cd directory && $(MAKE) clean
CLEANCMD2 = cd file && $(MAKE) clean

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
