.SILENT:

all:
	$(MAKE) -C bzlib
	$(MAKE) -C fribidi2
	$(MAKE) -C libiconv
	$(MAKE) -C libjpeg
	$(MAKE) -C libpng
	$(MAKE) -C libxml
	$(MAKE) -C libz

clean:
	$(MAKE) -C bzlib clean
	$(MAKE) -C fribidi2 clean
	$(MAKE) -C libiconv clean
	$(MAKE) -C libjpeg clean
	$(MAKE) -C libpng clean
	$(MAKE) -C libxml clean
	$(MAKE) -C libz clean
