########## smooth directory $(MAKE)file ##########

all:
	cd backends && $(MAKE)
	cd basic && $(MAKE)
	cd errors && $(MAKE)
	cd files && $(MAKE)
	cd graphics && $(MAKE)
	cd gui && $(MAKE)
	cd i18n && $(MAKE)
	cd input && $(MAKE)
	cd io && $(MAKE)
	cd misc && $(MAKE)
	cd net && $(MAKE)
	cd system && $(MAKE)
	cd threads && $(MAKE)
	cd xml && $(MAKE)

clean:
	cd backends && $(MAKE) clean
	cd basic && $(MAKE) clean
	cd errors && $(MAKE) clean
	cd files && $(MAKE) clean
	cd graphics && $(MAKE) clean
	cd gui && $(MAKE) clean
	cd i18n && $(MAKE) clean
	cd input && $(MAKE) clean
	cd io && $(MAKE) clean
	cd misc && $(MAKE) clean
	cd net && $(MAKE) clean
	cd system && $(MAKE) clean
	cd threads && $(MAKE) clean
	cd xml && $(MAKE) clean
