########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../..

# Change these variables to fit your project:
LOCALEXE  = widgettest

# Enter object files here:
OBJECTS	  = widgettest.o

# Enter additional library dependencies here
LIBS	  = widget/libmyactivearea.a

# Enter addition commands for targets all and clean here:
ALLCMD1   = cd widget && make
ALLCMD2   =
ALLCMD3   =
CLEANCMD1 = cd widget && make clean
CLEANCMD2 =
CLEANCMD3 =

## Do not change anything below this line. ##

include $(dir $(firstword $(MAKEFILE_LIST)))/$(SMOOTH_PATH)/Makefile-commands
