########## smooth directory makefile ##########

all:
	cd application && make
	cd dialogs && make
	cd mdi && make
	cd widgets && make
	cd window && make

clean:
	cd application && make clean
	cd dialogs && make clean
	cd mdi && make clean
	cd widgets && make clean
	cd window && make clean
