########## smooth directory $(MAKE)file ##########

all:
	cd application && $(MAKE)
	cd clipboard && $(MAKE)
	cd dialogs && $(MAKE)
	cd mdi && $(MAKE)
	cd widgets && $(MAKE)
	cd window && $(MAKE)

clean:
	cd application && $(MAKE) clean
	cd clipboard && $(MAKE) clean
	cd dialogs && $(MAKE) clean
	cd mdi && $(MAKE) clean
	cd widgets && $(MAKE) clean
	cd window && $(MAKE) clean
