########## smooth directory makefile ##########

all:
	cd beatclock && make
	cd mditest && make
	cd test && make
	cd testkey && make
	cd widgettest && make

clean:
	cd beatclock && make clean
	cd mditest && make clean
	cd test && make clean
	cd testkey && make clean
	cd widgettest && make clean
