########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../..

# Change these variables to fit your project:
LOCALEXE  = testkey

# Enter object files here:
OBJECTS	  = testkey.o

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
ALLCMD3   =
CLEANCMD1 =
CLEANCMD2 =
CLEANCMD3 =

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
