 /* The smooth Class Library
  * Copyright (C) 1998-2003 Robert Kausch <robert.kausch@gmx.net>
  *
  * This library is free software; you can redistribute it and/or
  * modify it under the terms of the "Artistic License".
  *
  * THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
  * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. */

#ifndef _H_CALLBACKS_
#define _H_CALLBACKS_

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback0
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance0
#define CALLBACKS_CONDITIONAL_COMMA
#define CALLBACKS_ARGUMENT_LIST
#define CALLBACKS_ARGUMENT_TYPES
#define CALLBACKS_ARGUMENT_PARAMETER_LIST
#define CALLBACKS_ARGUMENT_PARAMETERS
#define CALLBACKS_ARGUMENT_INV_PARAMETERS
#define CALLBACKS_VA_ARGUMENTS

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback1
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance1
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1
#define CALLBACKS_ARGUMENT_TYPES		pt1
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1
#define CALLBACKS_ARGUMENT_PARAMETERS		p1
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback2
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance2
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback3
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance3
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2, class pt3
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2, pt3
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2, pt3 p3
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2, p3
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p3, p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2), va_arg(ap, pt3)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback4
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance4
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2, class pt3, class pt4
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2, pt3, pt4
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2, pt3 p3, pt4 p4
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2, p3, p4
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p4, p3, p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2), va_arg(ap, pt3), va_arg(ap, pt4)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback5
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance5
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2, class pt3, class pt4, class pt5
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2, pt3, pt4, pt5
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2, pt3 p3, pt4 p4, pt5 p5
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2, p3, p4, p5
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p5, p4, p3, p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2), va_arg(ap, pt3), va_arg(ap, pt4), va_arg(ap, pt5)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback6
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance6
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2, class pt3, class pt4, class pt5, class pt6
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2, pt3, pt4, pt5, pt6
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2, pt3 p3, pt4 p4, pt5 p5, pt6 p6
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2, p3, p4, p5, p6
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p6, p5, p4, p3, p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2), va_arg(ap, pt3), va_arg(ap, pt4), va_arg(ap, pt5), va_arg(ap, pt6)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback7
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance7
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2, class pt3, class pt4, class pt5, class pt6, class pt7
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2, pt3, pt4, pt5, pt6, pt7
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2, pt3 p3, pt4 p4, pt5 p5, pt6 p6, pt7 p7
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2, p3, p4, p5, p6, p7
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p7, p6, p5, p4, p3, p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2), va_arg(ap, pt3), va_arg(ap, pt4), va_arg(ap, pt5), va_arg(ap, pt6), va_arg(ap, pt7)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#define CALLBACKS_CALLBACK_CLASS_NAME		Callback8
#define CALLBACKS_INSTANCE_CLASS_NAME		CInstance8
#define CALLBACKS_CONDITIONAL_COMMA		,
#define CALLBACKS_ARGUMENT_LIST			class pt1, class pt2, class pt3, class pt4, class pt5, class pt6, class pt7, class pt8
#define CALLBACKS_ARGUMENT_TYPES		pt1, pt2, pt3, pt4, pt5, pt6, pt7, pt8
#define CALLBACKS_ARGUMENT_PARAMETER_LIST	pt1 p1, pt2 p2, pt3 p3, pt4 p4, pt5 p5, pt6 p6, pt7 p7, pt8 p8
#define CALLBACKS_ARGUMENT_PARAMETERS		p1, p2, p3, p4, p5, p6, p7, p8
#define CALLBACKS_ARGUMENT_INV_PARAMETERS	p8, p7, p6, p5, p4, p3, p2, p1
#define CALLBACKS_VA_ARGUMENTS			va_arg(ap, pt1), va_arg(ap, pt2), va_arg(ap, pt3), va_arg(ap, pt4), va_arg(ap, pt5), va_arg(ap, pt6), va_arg(ap, pt7), va_arg(ap, pt8)

#include "templates/callbacks/callbackn.h"

#undef CALLBACKS_CALLBACK_CLASS_NAME
#undef CALLBACKS_INSTANCE_CLASS_NAME
#undef CALLBACKS_CONDITIONAL_COMMA
#undef CALLBACKS_ARGUMENT_LIST
#undef CALLBACKS_ARGUMENT_TYPES
#undef CALLBACKS_ARGUMENT_PARAMETER_LIST
#undef CALLBACKS_ARGUMENT_PARAMETERS
#undef CALLBACKS_ARGUMENT_INV_PARAMETERS
#undef CALLBACKS_VA_ARGUMENTS

#endif
