 /* The smooth Class Library
  * Copyright (C) 1998-2004 Robert Kausch <robert.kausch@gmx.net>
  *
  * This library is free software; you can redistribute it and/or
  * modify it under the terms of "The Artistic License, Version 2.0".
  *
  * THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
  * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. */

#ifndef _H_OBJSMOOTH_METRICS_
#define _H_OBJSMOOTH_METRICS_

#include "system.h"

namespace smooth
{
	const Int	 SMT_UNITS = 0;
	const Int	 SMT_PIXELS = 1;

#ifdef __SMOOTH_DLL__
	extern Int	 METRIC_TITLEBARHEIGHT;
	extern Int	 METRIC_TBBUTTONBOXOFFSETX;
	extern Int	 METRIC_TBBUTTONBOXOFFSETY;
	extern Int	 METRIC_TBBUTTONBOXWIDTH;
	extern Int	 METRIC_TBBUTTONBOXHEIGHT;
	extern Int	 METRIC_TBBUTTONSIZE;
	extern Int	 METRIC_TBBUTTONOFFSETX;
	extern Int	 METRIC_TBBUTTONOFFSETY;
	extern Int	 METRIC_TBTEXTOFFSETX;
	extern Int	 METRIC_TBTEXTOFFSETY;
	extern Int	 METRIC_TBICONSIZE;
	extern Int	 METRIC_TBICONOFFSET;

	extern Int	 METRIC_MENUBARHEIGHT;
	extern Int	 METRIC_MBTEXTOFFSETX;
	extern Int	 METRIC_MBTEXTOFFSETY;
	extern Int	 METRIC_MBENTRYSPACING;
	extern Int	 METRIC_MBENTRYHEIGHT;

	extern Int	 METRIC_IBICONOFFSETX;
	extern Int	 METRIC_IBICONOFFSETY;
	extern Int	 METRIC_IBICONSIZE;
	extern Int	 METRIC_IBENTRYSPACING;
	extern Int	 METRIC_IBARROWSIZEX;
	extern Int	 METRIC_IBARROWSIZEY;

	extern Int	 METRIC_STATUSBARHEIGHT;
	extern Int	 METRIC_SBTEXTOFFSETX;
	extern Int	 METRIC_SBTEXTOFFSETY;

	extern Int	 METRIC_PBTEXTOFFSETY;

	extern Int	 METRIC_GBTEXTOFFSETY;

	extern Int	 METRIC_POPUPENTRYSIZE;
	extern Int	 METRIC_POPUPARROWOFFSETY;

	extern Int	 METRIC_CHECKBOXOFFSETXY;
	extern Int	 METRIC_CHECKBOXTEXTOFFSETY;

	extern Int	 METRIC_OPTBOXOFFSETXY;
	extern Int	 METRIC_OPTBOXTEXTOFFSETY;

	extern Int	 METRIC_EDITBOXLINEHEIGHT;

	extern Int	 METRIC_COMBOBOXOFFSETX;
	extern Int	 METRIC_COMBOBOXARROWOFFSETY;
	extern Int	 METRIC_COMBOBOXARROWOFFSETX;
	extern Int	 METRIC_COMBOBOXTEXTOFFSETXY;

	extern Int	 METRIC_REGISTEROFFSETY;
	extern Int	 METRIC_REGISTERTEXTOFFSETX;
	extern Int	 METRIC_REGISTERTEXTOFFSETY;

	extern Int	 METRIC_TREEVIEWENTRYHEIGHT;

	extern Int	 METRIC_SLIDERAREAWIDTH;
	extern Int	 METRIC_SLIDERAREAHEIGHT;
	extern Int	 METRIC_SLIDERAREAOFFSETX;
	extern Int	 METRIC_SLIDERAREAOFFSETY;

	extern Int	 METRIC_LISTBOXENTRYHEIGHT;
	extern Int	 METRIC_LISTBOXTEXTOFFSETXY;
	extern Int	 METRIC_LISTBOXSBOFFSET;

	Void SetMetrics();
#endif

	SMOOTHAPI Void SetMeasurement(Int);
};

#endif
