########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../../..

# Enter object files here:
OBJECTS	  = activearea.o arrows.o button.o checkbox.o client.o divider.o editbox.o groupbox.o hyperlink.o image.o multiedit.o optionbox.o progressbar.o scrollbar.o slider.o statusbar.o tabwidget.o text.o titlebar.o

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
