########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ../../..

# Enter object files here:
OBJECTS	  = clipboard.o

# Enter addition commands for targets all and clean here:
ALLCMD1   = cd backends && make
CLEANCMD1 = cd backends && make clean

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands
