########## smooth directory makefile ##########

# Change these variables to fit this location:
SMOOTH_PATH = ..

# Enter object files here:
OBJECTS	  = smooth.h.gch

## Do not change anything below this line. ##

include $(SMOOTH_PATH)/Makefile-directories
include $(SMOOTH_PATH)/Makefile-commands

smooth.h.gch:
	$(CPPC) $(CPPCOPTS) -c smooth.h -o $@
