########## smooth directory $(MAKE)file ##########

all:
	cd image && $(MAKE)
	cd list && $(MAKE)
	cd menu && $(MAKE)
	cd tree && $(MAKE)

clean:
	cd image && $(MAKE) clean
	cd list && $(MAKE) clean
	cd menu && $(MAKE) clean
	cd tree && $(MAKE) clean
