########## smooth directory makefile ##########

all:
	cd image && make
	cd list && make
	cd menu && make
	cd tree && make

clean:
	cd image && make clean
	cd list && make clean
	cd menu && make clean
	cd tree && make clean
