########## smooth directory makefile ##########

all:
	cd designer && $(MAKE)
	cd pciffmanager && $(MAKE)
	cd translator && $(MAKE)

clean:
	cd designer && $(MAKE) clean
	cd pciffmanager && $(MAKE) clean
	cd translator && $(MAKE) clean
