########## smooth directory makefile ##########

all:
	cd designer && make
	cd pciffmanager && make
	cd translator && make

clean:
	cd designer && make clean
	cd pciffmanager && make clean
	cd translator && make clean
